/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

// import * as THREE from 'three';
import React, { useRef, useState } from 'react';
import { useLoader } from 'react-three-fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { draco, Html } from 'drei';

import { useSpring } from '@react-spring/core';
import { a } from '@react-spring/three';

export default function Car(props) {

  const [expand, setExpand] = useState(false);
  // React spring expand animation
  const animatedProps = useSpring({
    hovered: expand ? [1.5, 1.5, 1.5] : [1, 1, 1],
  });

  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/car.glb', draco('/draco-gltf/'))
  return (
    <group ref={group} {...props} dispose={null}>
      <a.group 
        position={[-5, -1.5, 0.8]}
        rotation={[0.2, -1.1, 0]}
        scale={animatedProps.hovered}
        onPointerOver={() => setExpand(true)}
        onPointerOut={() => setExpand(false)}
      >
        <mesh material={materials.car_body} geometry={nodes['Untitled.002_0'].geometry} />
        <mesh material={materials.car_glass} geometry={nodes['Untitled.002_1'].geometry} />
        <mesh material={materials.car_tire} geometry={nodes['Untitled.002_2'].geometry} />
      </a.group>
      <Html scaleFactor={5} position={[-4.5, -2.5, 1]}>
        <h1 style={{ color: 'white', opacity: '0.2' }}>About</h1>
      </Html>
    </group>
  )
}
