/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { draco } from 'drei'
// import { a, useSpring } from 'react-spring'

function JacketOne(props) {

  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/jacketDraco.glb', draco('/draco-gltf/'))

  return (
    <group ref={group} {...props} dispose={null} >
      <mesh
        material={materials.Material}
        geometry={nodes.Top.geometry}
        position={[0, -5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.04, 0.04, 0.04]}
      />
    </group>
  )
}

export default JacketOne;