/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: IUPUI Center for Digital Scholarship (https://sketchfab.com/iupuicds)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/7621684c2e704a0b93579795f42d90da
title: University Library - T-Shirt - White
*/

// import * as THREE from 'three'
import React, { useRef, useState } from 'react';
import { useLoader } from 'react-three-fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { draco, Html } from 'drei';
import { a, useSpring } from 'react-spring/three';


export default function Shirt(props) {

  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/scene.gltf', draco('/draco-gltf/'))

  const [expand, setExpand] = useState(false);
  // React spring expand animation
  const animatedProps = useSpring({
    hovered: expand ? [0.008, 0.008, 0.007] : [0.009, 0.009, 0.008],
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 1]} position={[3.5, -3.5, 2]}>
        <a.group 
          rotation={[0, 0.03, 3.11]} 
          scale={animatedProps.hovered}
          onPointerOver={() => setExpand(!expand)}
        >
          <mesh material={materials.material_0} geometry={nodes.mesh_0.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_1.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_2.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_3.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_4.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_5.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_6.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_7.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_8.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_9.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_10.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_11.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_12.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_13.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_14.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_15.geometry} />
          <Html scaleFactor={5} position={[ 0, -2.5, 0 ]}>
            <h1 style={{ color: 'white', opacity: '0.2' }}>Shop</h1>
          </Html>
        </a.group>
      </group>
    </group>
  )
}
